#
#server:
#  port: 8080
#  tomcat.uri-encoding: UTF-8
#
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true # beetles_chatroom_db
#    username: root
#    password: 123456

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beetles_chatroom_db?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

#    username: beetles
#    password: beetles123456
